version: 1.0.0
services:
  - mysql
events:
  build:
    steps:
      -
        composer:
          type: script
          script:
            - 'composer install --no-interaction'
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 2'
            - 'cd ..'
            - ./vendor/bin/behat
      # The "deploy" step runs the proof-of-concept code. Later, this
      # functionality will be built into Pipelines directly and controlled via
      # YAML.
      - deploy:
          script:
            - cd environments
            - composer install
            - php cloud-ode.php
variables:
  global:
    N3_KEY: 56a87bdc-64eb-4196-bdd9-2d5fa4c2906c
    VALIDATION_TOKEN:
      secure: 2acfIynfp734BVEt7dyeeacJxZiMPl0SBUMz9k0gWbWvHrrpBgshuIA3BsEhLfM/RwiMmaYjxv9f0ndYcr4K5SlxJlydGLGwEVb5pOFEbhVqnhBjm369TLpYW9Z3Q9VNK19vHs/suYVCtF1IGaL+P4xT/WgiR+Jk+ctJytDYWHHOj/F3cnJumzcRVAovch+nIKGcNAVO0HCCcFmqzoVrTl6PcYQWnVN8CcrnL/BWDtNuCxM5cNmnd9Yi1Nlr/uIEZC6bQcqGC9NF8Gpx302cnzp0EaWLlIKaGt0u7mHEjL9E4WXmJVPIlKuoQ9Z9Jn2RyKke3kZAg+2xitr/FKUiQghYywUW6FJeGgHschpKSt213e0LQlcxUXbcfcy5rmUOFVkmTa08ngM/vFfZhUJ2QlNI1+jBw8elYQMBEusPO9QUPfXYkFE2ryUwpEiPu3IKNEAJ2oKiNgaEl6+1U6k4gjE98VTYvvirAOaq1bi3AB+zvNs820FCLnJm4nuZeanDExcreKWUhg/Mtbm7xLmlIdRLxETfv+dVJ+ciSQybzX0YPQevz8GTFOWErKsX14RkyqUsbtpIqy5vXE4L7TzZeBqV3LAt2FQPwADHqY2a0wzdEVgks0+GuwsDySFP0CCKHsq8t/awiouJzhX2LkZ36mShoO1vC3Q8LuH1NtlL+rnYac=8rhS4s3Jd7/apYNHxSh7UXzhjamSLMqk+ht49aQw7Mi8UG4bbx/JeHoiK7Gokzm/
    N3_SECRET:
      secure: 2acUmbaZJC2pziEY3gva53JTLV8N4z0NIoKGwgM7HGCP7BLpLXUTadfQFGq0LQjRwMyPdiT0v9yg4QwSEqVPxANdKC6M0dqI3GtJuDwCYthHCiKn7DE4Jxr2/VumLbbPF/w/FV0ceCY006A56D3SImXKcA23UYe5wq4MxqIA7uUa8lE1JZIo6+KGifCbJyHe/FN4K4U5HEBUDryDkJftPytJWU10xdKZB61X+IyL7mRAAlEmIxCS+JOqs/OEBjTpZz1XqqRjAYFuUIe9UCEgB+tGR6BZXcVW+dCEqLOeoX8Tuo4Z0nbwxow9bfCwp2Bnpe6QfkBNGiiZcjC4kzRu/ewzSHvYgWz9xAoUPL/GATXJADRBB0XCnTKvvmvLJVREJWMF86tg1YmE45rnsEbufhm2AkZ3i80ooZU+FpwnMI4ojgxDS7J84wcz26gKyTtEkp53xMv7TXQj77LRfWPA7bVgOaWkAb5C+HRrHmrnFG9jU8HmbMlGLcB6P69bxwTzsw/inm4uokmkhkyUSMk+Yg3Or02bn8T4OkvhTUOoBTvH61Wbp7QRWKK73xYTReQPxDALQvbWn9WXVl66zwWFHp2PIdfg5WCqOSKewOaY77Mo116XUAKTc2QRa2gmTeHWO/X+20+wIos9+2vl/PUjmOUm0Jypk0dK5TUpf/MFAqbspE=RjRMW+3e6ImY1URNsTEAlgctuEyth/2XtFyr7kLeSoazKxDaXkVnzZPIxzYE0RDd
